name: salad
channels:
  - defaults
  - xformers
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch==2.1.0
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision==0.16.0
  - xformers
